In [13]:
import pandas as pd
data = pd.read_csv('Crime_Data_from_2020_to_2024.csv')

In [6]:
data.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON'],
      dtype='object')

,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Crm Cd,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Premis Cd,Premis Desc,Weapon Used Cd,Weapon Desc,Status,Crm Cd 1,LOCATION
0,04/11/2021 12:00:00 AM,11/07/2020 12:00:00 AM,845,15,N Hollywood,1502,354,THEFT OF IDENTITY,31,M,H,501.0,SINGLE FAMILY DWELLING,NaN,NaN,IC,354.0,7800 BEEMAN AV
1,10/21/2020 12:00:00 AM,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1521,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",32,M,H,102.0,SIDEWALK,200.0,KNIFE WITH BLADE 6INCHES OR LESS,IC,230.0,ATOLL AV
2,12/10/2024 12:00:00 AM,10/30/2020 12:00:00 AM,1240,9,Van Nuys,933,354,THEFT OF IDENTITY,30,M,W,501.0,SINGLE FAMILY DWELLING,NaN,NaN,IC,354.0,14600 SYLVAN ST
3,12/24/2020 12:00:00 AM,12/24/2020 12:00:00 AM,1310,7,Wilshire,782,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,47,F,A,101.0,STREET,NaN,NaN,IC,331.0,6000 COMEY AV
4,10/03/2020 12:00:00 AM,09/29/2020 12:00:00 AM,1830,14,Pacific,1454,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),63,M,H,103.0,ALLEY,NaN,NaN,IC,420.0,4700 LA VILLA MARINA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004889,07/24/2024 12:00:00 AM,07/23/2024 12:00:00 AM,1400,7,Wilshire,788,510,VEHICLE - STOLEN,0,NaN,NaN,101.0,STREET,NaN,NaN,IC,510.0,4000 W 23RD ST
1004890,01/15/2024 12:00:00 AM,01/15/2024 12:00:00 AM,100,1,Central,101,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0,X,X,503.0,HOTEL,500.0,UNKNOWN WEAPON/OTHER WEAPON,IC,745.0,1300 W SUNSET BL
1004891,10/14/2024 12:00:00 AM,10/11/2024 12:00:00 AM,2330,4,Hollenbeck,421,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",29,M,B,210.0,RESTAURANT/FAST FOOD,NaN,NaN,IC,341.0,1700 ALBION ST
1004892,04/24/2024 12:00:00 AM,04/24/2024 12:00:00 AM,1500,3,Southwest,358,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",70,F,W,102.0,SIDEWALK,308.0,STICK,IC,230.0,FLOWER ST
1004893,08/13/2024 12:00:00 AM,08/12/2024 12:00:00 AM,2300,9,Van Nuys,914,510,VEHICLE - STOLEN,0,NaN,NaN,108.0,PARKING LOT,NaN,NaN,IC,510.0,6900 VESPER AV

In [26]:
data['Date Rptd'] = pd.to_datetime(data['Date Rptd'], format = "%m/%d/%Y %H:%M:%S %p")

In [29]:
newData = data.loc[data['Date Rptd'].dt.year <= 2020]
newData

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
1,201516622,2020-10-21 12:00:00,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203
3,210704711,2020-12-24 12:00:00,12/24/2020 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747
4,201418201,2020-10-03 12:00:00,09/29/2020 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350
7,201115217,2020-10-29 12:00:00,07/07/2020 12:00:00 AM,1400,11,Northeast,1133,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,...,AO,Adult Other,812.0,860.0,NaN,NaN,3000 ACRESITE ST,NaN,34.1107,-118.2589
12,202113531,2020-09-06 12:00:00,09/05/2020 12:00:00 AM,1500,21,Topanga,2149,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,NaN,NaN,NaN,19700 VANOWEN ST,NaN,34.1938,-118.5631
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199849,202000740,2020-11-14 12:00:00,11/12/2020 12:00:00 AM,2200,20,Olympic,2058,2,805,PIMPING,...,IC,Invest Cont,805.0,998.0,NaN,NaN,900 ELDEN AV,NaN,34.0550,-118.2878
199852,200814601,2020-09-28 12:00:00,08/25/2020 12:00:00 AM,1900,8,West LA,819,2,860,BATTERY WITH SEXUAL CONTACT,...,AO,Adult Other,860.0,NaN,NaN,NaN,10200 CHARING CROSS RD,NaN,34.0793,-118.4299
199854,201008363,2020-04-24 12:00:00,04/24/2020 12:00:00 AM,628,10,West Valley,1005,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,AA,Adult Arrest,740.0,NaN,NaN,NaN,17700 ROSCOE BL,NaN,34.2210,-118.5186
199856,201000596,2020-03-11 12:00:00,03/11/2020 12:00:00 AM,2245,10,West Valley,1034,1,310,BURGLARY,...,AA,Adult Arrest,310.0,998.0,NaN,NaN,6100 RESEDA BL,NaN,34.1807,-118.5360
199857,201016292,2020-12-22 12:00:00,12/21/2020 12:00:00 AM,1400,10,West Valley,1031,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,AO,Adult Other,420.0,998.0,NaN,NaN,6200 BELMAR AV,NaN,34.1836,-118.5582